# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main
      - develop
      - release/*
      - hotfix/*
  paths:
    exclude:
      - .vscode/**/*
      - .editorconfig
      - .eslintrc.js
      - .gitignore
      - README.md

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '20.x'

  - task: Npm@1
    displayName: 'NPM Install'
    inputs:
      command: 'install'

  - task: CopyFiles@2
    displayName: 'Generate Build Artifacts'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        **/*
        !.git/**/*
        !.vscode/**/*
        !.gitignore
        !.eslintrc.js
        !.editorconfig
        !node_modules/**/*
        !scripts/**/*
        !test/**/*
        !azure-pipelines.yml
        !README.md
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
