import {
  AlertTriangle,
  ArrowRight,
  Building2,
  CalendarCheck2,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideIcon,
  LucideShoppingBag,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  UserCircle2Icon,
  UserPen,
  UserX2Icon,
  X,
  WaypointsIcon,
  RocketIcon,
  ListCheckIcon,
  BugIcon,
  FlaskConicalIcon,
  BookUserIcon,
  BrainCircuitIcon,
  BrainCogIcon,
  BookMarkedIcon,
  FileType2Icon,
  LanguagesIcon
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  product: LucideShoppingBag,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX2Icon,
  post: FileText,
  page: File,
  userPen: UserPen,
  user2: UserCircle2Icon,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  institution: Building2,
  calendar: CalendarCheck2,
  demand: WaypointsIcon,
  release: RocketIcon,
  checklist: ListCheckIcon,
  issue: BugIcon,
  lab: FlaskConicalIcon,
  curriculum: BookUserIcon,
  skill: BrainCircuitIcon,
  practice: BrainCogIcon,
  document: FileType2Icon,
  wiki: BookMarkedIcon,
  locale: LanguagesIcon,
  check: Check
};
